packages:
  - apps/*
  - packages/*
  - tools/*
  - packages/ui/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  react: ^19.2.8
  react-dom: ^19.2.8
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@ionic/react": ^8.8.15
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
