export const RELATIONSHIP_OPTIONS = [
  "Grandfather",
  "Grandmother",
  "Father",
  "Mother",
  "Son",
  "Daughter",
  "Brother",
  "Sister",
  "Grandson",
  "Granddaughter",
  "Husband",
  "Wife",
  "Uncle",
  "Aunt",
  "Cousin",
  "Father-in-law",
  "Mother-in-law",
  "Son-in-law",
  "Daughter-in-law",
  "Friend",
  "Other",
] as const;
